{% set data = load_setup_py_data() %}

package:
  name: pcgr
  version: {{ data.get('version') }}

source:
  path: ../../..

build:
  number: 0
  noarch: python

requirements:
  build:
    - curl
    - unzip
    - tar
    - python ==3.10
  run:
    - python ==3.10
    - pandas
    - scipy
    - pip

test:
  commands:
    - pcgr --version

about:
  home: {{ data.get('url') }}
  license: {{ data.get('license') }}
  summary: {{ data.get('description') }}
