package:
  name: pcgr
  version: 0.9.4

source:
  path: ../../..

build:
  number: 0
  noarch: python

requirements:
  build:
    - curl
    - unzip
    - tar
    - python ==3.7.12
  run:
    - python ==3.7.12
    - pandas
    - scipy

test:
  commands:
    - pcgr --version

about:
  home: https://github.com/sigven/pcgr
  license: MIT
  summary: Personal Cancer Genome Reporter (PCGR) - variant interpretation report for precision cancer medicine
