{% set name = 'pcgr' %}
{% set version = '0.9.2' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../..

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - curl
    - unzip
    - tar
    - pip
    - python ==3.7.12
  run:
    - python ==3.7.12
    - bedtools ==2.30.0
    - cyvcf2 ==0.30.11
    - ensembl-vep ==104.3
    - htslib ==1.10.2
    - pandas
    - scipy
    - vcfanno ==0.3.3
    - vt
    - vcf2maf ==1.6.21

test:
  commands:
    - pcgr --version

about:
  home: https://github.com/sigven/pcgr
  license: MIT
  summary: Personal Cancer Genome Reporter (PCGR) - variant interpretation report for precision cancer medicine
