{% set name = 'pcgr' %}
{% set version = '0.9.2' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - curl
    - unzip
    - tar
    - pip
    - python ==3.7
    - r-base ==4.0.5
    - r-pcgrr
  run:
    - python ==3.7
    - r-base ==4.0.5
    - r-pcgrr
    - ensembl-vep ==104.3
    - cython ==0.29.24
    - scipy ==1.7.3
    - pandas ==1.3.4
    - htslib ==1.10.2
    - cyvcf2 ==0.30.11
    - bedtools ==2.30.0
    - vcfanno ==0.3.3
    - vt ==0.57721
    - vcf2maf ==1.6.18

test:
  commands:
    - pcgr --version
    - $R -e "library('pcgrr')"

about:
  home: https://github.com/sigven/pcgr
  license: MIT
  summary: Personal Cancer Genome Reporter (PCGR) - variant interpretation report for precision cancer medicine
