name: mambabuild

on:
  push:
    branches:
      - master
      - dev

jobs:
  build-conda:
    # When merging to one of the branches above and the commit message matches
    #if: "startsWith(github.event.head_commit.message, 'CI Test')"
    if: "startsWith(github.event.head_commit.message, 'Bump version:')"
    name: Build conda packages
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: 4.11.0-0
          show-channel-urls: true
          auto-activate-base: false
          activate-environment: condabuild
          environment-file: conda/env/yml/condabuild.yml
          use-mamba: true
      - name: Build + upload pcgr/pcgrr conda pkgs
        run: |
          conda mambabuild conda/recipe/pcgr -c conda-forge -c bioconda --token ${{ secrets.ANACONDA_UPLOAD_TOKEN }}
          conda mambabuild conda/recipe/pcgrr -c conda-forge -c bioconda --token ${{ secrets.ANACONDA_UPLOAD_TOKEN }}
