name: pkgdown
on:
  push:
    branches:
      - pkgdown

env:
  env_yml_path: conda/env/yml

jobs:
  pkgdown-site:
    name: Deploy pkgdown website
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          # Do everything inside the base env
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""
          mamba-version: "*"
          channels: "pcgr,conda-forge,bioconda"
      - name: Install conda packages
        run: mamba env create -n pkgdown -f ${env_yml_path}/pkgdown.yml
      - name: Publish pkgdown website
        run: |
            git config --local user.email "actions@github.com"
            git config --local user.name "GitHub Actions"
            conda activate pkgdown
            printf "pcgrr version:\n"
            Rscript -e "packageVersion('pcgrr')"
            Rscript -e "pkgdown::deploy_to_branch(pkg = 'pcgrr', commit_message = paste(pkgdown:::construct_commit_message('.'), '- see https://umccr.github.io/pcgr/'), branch = 'gh-pages', new_process = FALSE)"
